//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBHansIVCupCompetEntities : DbContext
    {
        public DBHansIVCupCompetEntities()
            : base("name=DBHansIVCupCompetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBestOfTrois> tblBestOfTrois { get; set; }
        public virtual DbSet<tblcartes> tblcartes { get; set; }
        public virtual DbSet<tblCauseFinBo3> tblCauseFinBo3 { get; set; }
        public virtual DbSet<tblEquipeParticipeBO3> tblEquipeParticipeBO3 { get; set; }
        public virtual DbSet<tblJoueur> tblJoueur { get; set; }
        public virtual DbSet<tblJoueurTeam> tblJoueurTeam { get; set; }
        public virtual DbSet<tblJoueurTeamParticipeBO3> tblJoueurTeamParticipeBO3 { get; set; }
        public virtual DbSet<tblPartie> tblPartie { get; set; }
        public virtual DbSet<tblRegionTeam> tblRegionTeam { get; set; }
        public virtual DbSet<tblRoleMembreTeam> tblRoleMembreTeam { get; set; }
        public virtual DbSet<tblSaison> tblSaison { get; set; }
        public virtual DbSet<tblTeam> tblTeam { get; set; }
        public virtual DbSet<tblTeamParticipePartie> tblTeamParticipePartie { get; set; }
        public virtual DbSet<tblTeamParticipeSaison> tblTeamParticipeSaison { get; set; }
    }
}
