//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipeParticipeBO3
    {
        public int idParticipationBo3 { get; set; }
        public int idBo3 { get; set; }
        public int idTeam { get; set; }
    
        public virtual tblBestOfTrois tblBestOfTrois { get; set; }
        public virtual tblTeam tblTeam { get; set; }
    }
}
