//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJoueurTeamParticipeBO3
    {
        public int idParticipant { get; set; }
        public int idJoueur { get; set; }
        public int idTeam { get; set; }
        public int idBO3 { get; set; }
        public bool participationConfirmee { get; set; }
    
        public virtual tblBestOfTrois tblBestOfTrois { get; set; }
        public virtual tblJoueur tblJoueur { get; set; }
        public virtual tblTeam tblTeam { get; set; }
    }
}
