//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJoueur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJoueur()
        {
            this.tblJoueurTeam = new HashSet<tblJoueurTeam>();
            this.tblJoueurTeamParticipeBO3 = new HashSet<tblJoueurTeamParticipeBO3>();
        }
    
        public int idJoueur { get; set; }
        public string idDiscord { get; set; }
        public string pseudoUplay { get; set; }
        public string pseudoDiscord { get; set; }
        public string noPseudoDiscord { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJoueurTeam> tblJoueurTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJoueurTeamParticipeBO3> tblJoueurTeamParticipeBO3 { get; set; }
    }
}
