//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPartie()
        {
            this.tblTeamParticipePartie = new HashSet<tblTeamParticipePartie>();
        }
    
        public int idPartie { get; set; }
        public int idMap { get; set; }
        public Nullable<int> devaitEtreJouee { get; set; }
        public Nullable<int> idBO3 { get; set; }
    
        public virtual tblBestOfTrois tblBestOfTrois { get; set; }
        public virtual tblcartes tblcartes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeamParticipePartie> tblTeamParticipePartie { get; set; }
    }
}
