//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTeam()
        {
            this.tblEquipeParticipeBO3 = new HashSet<tblEquipeParticipeBO3>();
            this.tblJoueurTeam = new HashSet<tblJoueurTeam>();
            this.tblJoueurTeamParticipeBO3 = new HashSet<tblJoueurTeamParticipeBO3>();
            this.tblTeamParticipeSaison = new HashSet<tblTeamParticipeSaison>();
            this.tblTeamParticipePartie = new HashSet<tblTeamParticipePartie>();
        }
    
        public int idTeam { get; set; }
        public string nomTeam { get; set; }
        public int idRegion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEquipeParticipeBO3> tblEquipeParticipeBO3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJoueurTeam> tblJoueurTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJoueurTeamParticipeBO3> tblJoueurTeamParticipeBO3 { get; set; }
        public virtual tblRegionTeam tblRegionTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeamParticipeSaison> tblTeamParticipeSaison { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeamParticipePartie> tblTeamParticipePartie { get; set; }
    }
}
