//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeamParticipeSaison
    {
        public int idInscriptionSaison { get; set; }
        public int idTeam { get; set; }
        public int idSaison { get; set; }
        public int ptsTeam { get; set; }
        public bool inscriptionActive { get; set; }
    
        public virtual tblSaison tblSaison { get; set; }
        public virtual tblTeam tblTeam { get; set; }
    }
}
